name: novi_indus_machine_test
description: "A new Flutter machine test."

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  pdf: ^3.11.1
  intl: ^0.19.0
  path_provider: ^2.1.2

  #cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  flutter_lints: ^4.0.0
  


flutter:


  uses-material-design: true

  assets:
     - assets/empty_list.png
     - assets/logo.png

